// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalDetails() {
  return window['go']['main']['App']['GetLocalDetails']();
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}

export function RunScanner() {
  return window['go']['main']['App']['RunScanner']();
}

export function SendFileToServer(arg1, arg2) {
  return window['go']['main']['App']['SendFileToServer'](arg1, arg2);
}
