// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalDetails():Promise<{[key: string]: string}>;

export function RunScanner():Promise<void>;
